# Generated by Django 3.2.25 on 2026-01-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='fienddly_name',
            new_name='friendly_name',
        ),
    ]
